### PR TITLE
Fix/48 on success context type

### LINKED ISSUE #48: Generated code incompatible from  5.14.6 to 5.17.9 of @tanstack/react-query
Today when i have updated the @tanstack/react-query depenency, i found out that the latest compatible version is 5.13.4.

Changing the generated local code from: 

`ts
function useRapiniMutation<TData = unknown, TError = unknown, TVariables = void, TContext = unknown>(mutationFn: MutationFunction<TData, TVariables>, config?: (queryClient: QueryClient) => Pick<UseMutationOptions<TData, TError, TVariables, TContext>, "onSuccess" | "onSettled" | "onError">, options?: Omit<UseMutationOptions<TData, TError, TVariables, TContext>, "mutationFn">): UseMutationResult<TData, TError, TVariables, TContext> {
    const { onSuccess, onError, onSettled, ...rest } = options ?? {};
    const queryClient = useQueryClient();
    const conf = config?.(queryClient);
    const mutationOptions: typeof options = {
        onSuccess: (data: TData, variables: TVariables, context?: TContext) => {
            conf?.onSuccess?.(data, variables, context);
            onSuccess?.(data, variables, context);
        },
        onError: (error: TError, variables: TVariables, context?: TContext) => {
            conf?.onError?.(error, variables, context);
            onError?.(error, variables, context);
        },
        onSettled: (data: TData | undefined, error: TError | null, variables: TVariables, context?: TContext) => {
            conf?.onSettled?.(data, error, variables, context);
            onSettled?.(data, error, variables, context);
        },
        ...rest
    };
    return useMutation({ mutationFn, ...mutationOptions });
}
`

to 

`ts
function useRapiniMutation<TData = unknown, TError = unknown, TVariables = void, TContext = unknown>(mutationFn: MutationFunction<TData, TVariables>, config?: (queryClient: QueryClient) => Pick<UseMutationOptions<TData, TError, TVariables, TContext>, "onSuccess" | "onSettled" | "onError">, options?: Omit<UseMutationOptions<TData, TError, TVariables, TContext>, "mutationFn">): UseMutationResult<TData, TError, TVariables, TContext> {
    const { onSuccess, onError, onSettled, ...rest } = options ?? {};
    const queryClient = useQueryClient();
    const conf = config?.(queryClient);
    const mutationOptions: typeof options = {
        onSuccess: (data: TData, variables: TVariables, context: TContext) => {
            conf?.onSuccess?.(data, variables, context);
            onSuccess?.(data, variables, context);
        },
        onError: (error: TError, variables: TVariables, context?: TContext) => {
            conf?.onError?.(error, variables, context);
            onError?.(error, variables, context);
        },
        onSettled: (data: TData | undefined, error: TError | null, variables: TVariables, context?: TContext) => {
            conf?.onSettled?.(data, error, variables, context);
            onSettled?.(data, error, variables, context);
        },
        ...rest
    };
    return useMutation({ mutationFn, ...mutationOptions });
}
`

makes it compile again:

> onSuccess: (data: TData, variables: TVariables, context: TContext) => {
>            conf?.onSuccess?.(data, variables, context);
>           onSuccess?.(data, variables, context);
>       },

### PR DESCRIPTION
**Pull request by Aiglobelam**
# Fix #48 
As I never seen or worked with code generation before, I took help from ChatGPT Claude 3.5 Sonnnet (Preview) to do this PR. And the suggestions seems legit to me, but... yeah... I think you need to check them 😄 
BeforeAfter

contextNotOptional

# What?

Makes the context parameter required in onSuccess callback to match React Query's types.
This ensures type safety by properly matching React Query's API where context is:
- Required in onSuccess
- Optional in onError and onSettled

Note that ChatGPT suggested to revert the order of the `changelog.md` file... so I went with that, can undo that if you want.

- [x] I have added or updated unit tests for this change.
- [x] I have updated the [changelog](https://github.com/rametta/rapini/blob/main/changelog.md) with info about the changes in this PR

### CODE REVIEW

File: src/react-query/rapini-mutation.ts [hunk 1]
```diff
@@ -299,7 +299,7 @@ export function makeRapiniMutation() {
                             undefined,
                             undefined,
                             ts.factory.createIdentifier("context"),
-                            ts.factory.createToken(ts.SyntaxKind.QuestionToken),
+                            undefined,
```
Comment (nuanxed-lipecki) [inline src/react-query/rapini-mutation.ts:302]: lgtm :-)

**Comment by rametta** [comment]
Nice, thank you for the PR!
2 comments
- Please update the changelog file to just include the new change and the next version number, there seems to be a lot of changes to that file but we just need the new changes.
- Does this change force every use of onSuccess to pass in a context as the third argument? Or it fully hidden from the consumers? Been awhile since I used this so I can't remember if removing the optionality of the last argument will force everyone to start passing in a context whenever they want to use onSuccess. let me know!

Thanks!

**Comment by Aiglobelam** [comment]
I first located where in react-query release log this change was made

TAG: https://github.com/TanStack/query/releases/tag/v5.14.1
PR: https://github.com/TanStack/query/pull/6355

Then I also consulted the AI once more:

rapiniResp1

rapiniResp2

# Conclusion

This change matches React Query's own type changes from [this commit](https://github.com/TanStack/query/commit/320cf9bed2ba9b0167aaf6f622665df3859ceed9).

The commit removed optionality from `context` in `onSuccess` because it's only called when a mutation succeeds, and in that case React Query always provides the context that was passed to mutate.

Looking at our test file, we're already expecting this behavior:
```typescript
onSuccess: (data: TData, variables: TVariables, context: TContext) => {
    conf?.onSuccess?.(data, variables, context);
    onSuccess?.(data, variables, context);
}
```

This change:
1. Aligns our types with React Query's
2. Reflects the actual runtime behavior (context is always available in onSuccess)
3. Maintains optional context for onError/onSettled where it might be undefined
4. Doesn't change the API surface, just makes types more accurate

Users won't need to provide context explicitly - React Query handles that internally. The type change just ensures we correctly model what React Query guarantees.

**Review by rametta — APPROVED** [review]
